# Generated by Django 5.2.6 on 2025-11-21 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="notification",
            name="target_object_id",
        ),
    ]
