# Generated by Django 5.2.6 on 2025-11-20 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="id",
            new_name="post_id",
        ),
    ]
