# Generated by Django 5.2.6 on 2025-11-24 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0002_rename_id_post_post_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="link",
            field=models.URLField(blank=True, null=True),
        ),
    ]
